# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testcommit-manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create file
        run: |
          date +%s > date.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
