name: testperiodic

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  testcommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create file
        run: date +%s > date.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
